TravelProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace TravelProject.Controllers
{
    public class HomeController : Controller
    {
        //    private readonly ILogger<HomeController> _logger;

        //    public HomeController(ILogger<HomeController> logger)
        //    {
        //        _logger = logger;
        //    }

        public IActionResult Index()
        {
            return View();
        }

       
    }
}

TravelProject/ViewComponents/BlogViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Repository.Models;
using Repository.Repositories.ShoppingRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Travel.Models;

namespace Travel.ViewComponents
{
    public class BlogViewComponent :ViewComponent
    {
        private readonly IMapper _mapper;
        private readonly IProductRepository _productRepository;
        public BlogViewComponent(IMapper mapper,
                                IProductRepository productRepository)
        {
            _mapper = mapper;
            _productRepository = productRepository;
        }
        public IViewComponentResult Invoke()
        {
            var products = _productRepository.GetPopularDestination(8);
            var model = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products);
            return View(model);
        }
    }
}

TravelProject/ViewComponents/ExploreViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Repository.Models;
using Repository.Repositories.ShoppingRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Travel.Models;

namespace Travel.ViewComponents
{
    public class ExploreViewComponent : ViewComponent
    {
        private readonly IMapper _mapper;
        private readonly IProductRepository _productRepository;
        public ExploreViewComponent(IMapper mapper,
                                IProductRepository productRepository)
        {
            _mapper = mapper;
            _productRepository = productRepository;
        }
        public IViewComponentResult Invoke()
        {
            var products = _productRepository.GetHoneymoonProducts(8);
            var model = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products);
            return View(model);
        }
    }
}

TravelProject/ViewComponents/HoneymoonViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Repository.Models;
using Repository.Repositories.ShoppingRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Travel.Models;

namespace Travel.ViewComponents
{
    public class HoneymoonViewComponent :ViewComponent
    {
        private readonly IMapper _mapper;
        private readonly IProductRepository _productRepository;
        public HoneymoonViewComponent(IMapper mapper,
                                IProductRepository productRepository)
        {
            _mapper = mapper;
            _productRepository = productRepository;
        }
        public IViewComponentResult Invoke()
        {
            var products = _productRepository.GetSpecialNatureProducts(8);
            var model = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products);
            return View (model);
        }
    }
}

TravelProject/ViewComponents/TopSellingViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Repository.Models;
using Repository.Repositories.ShoppingRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Travel.Models;

namespace Travel.ViewComponents
{
    public class TopSellingViewComponent :ViewComponent
    {
        private readonly IMapper _mapper;
        private readonly IProductRepository _productRepository;
        public TopSellingViewComponent(IMapper mapper,
                                IProductRepository productRepository)
        {
            _mapper = mapper;
            _productRepository = productRepository;
        }
        public IViewComponentResult Invoke()
        {
            var products = _productRepository.GetTopSellingProducts(8);
            var model = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products);
            return View(model);
        }
    }
}

TravelProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<!-- home section start -->
<section class="home_section  p-0">
    <div class="classic-slider no-arrow">
        <div>
            <div class="home ripple-effect">
                <img src="~/images/tour-bg.jpg" class="img-fluid blur-up lazyload bg-img" alt="">
            </div>
        </div>
        <div>
            <div class="home ripple-effect">
                <img src="~/images/tour-bg1.jpg" class="img-fluid blur-up lazyload bg-img" alt="">
            </div>
        </div>
        <div>
            <div class="home ripple-effect">
                <img src="~/images/tour-bg.jpg" class="img-fluid blur-up lazyload bg-img" alt="">
            </div>
        </div>
    </div>
    <div class="offer-text">
        <h6>
            <span>s</span>
            <span>t</span>
            <span>a</span>
            <span>r</span>
            <span>t</span>
            <span></span>
            <span>y</span>
            <span>o</span>
            <span>u</span>
            <span>r</span>
            <span></span>
            <span>j</span>
            <span>o</span>
            <span>u</span>
            <span>n</span>
            <span>e</span>
            <span>y</span>
        </h6>
    </div>
</section>
<div class="error"></div>
<!-- home section end -->
<!-- book table section start -->
<section class="book-table section-b-space p-0 single-table">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="table-form">
                    <form>
                        <div class="row w-100">
                            <div class="form-group col p-0">
                                <input type="text" class="form-control" id="exampleFormControlInput1"
                                       placeholder="Starting from">
                                <img src="~/images/icon/table-no.png" class="img-fluid blur-up lazyload"
                                     alt="">
                            </div>
                            <div class="form-group col p-0">
                                <input type="text" class="form-control" placeholder="Going to">
                                <img src="~/images/icon/table-no.png" class="img-fluid blur-up lazyload"
                                     alt="">
                            </div>
                            <div class="col p-0">
                                <input placeholder="During Date" id="datepicker" />
                            </div>
                        </div>
                        <a href="#" class="btn btn-rounded color1">search</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- book table section end -->
<vc:top-selling></vc:top-selling>
<vc:honeymoon></vc:honeymoon>
<vc:awesome-packages></vc:awesome-packages>
<vc:special-nature></vc:special-nature>
<vc:explore></vc:explore>
<!-- gallery section start -->
<section class="gallery-section pt-0">
    <div class="container-fluid p-0">
        <div class="row zoom-gallery m-0">

            <div class="col-2 p-0">
                <a href="~/images/tour/gallery/2.jpg" class="img-box">
                    <div class="gallery_box">
                        <div class="gallery-img">
                            <div class="overlay"></div>
                            <img src="~/images/tour/gallery/2.jpg" alt=""
                                 class="img-fluid blur-up lazyload w-100">
                        </div>
                        <div class="gallery-content">
                            <h3>china town</h3>
                            <div class="rating">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="view-cls"><i class="fas fa-plus"></i></div>
                    </div>
                </a>
                <a href="~/images/tour/gallery/3.jpg" class="img-box">
                    <div class="gallery_box">
                        <div class="gallery-img">
                            <div class="overlay"></div>
                            <img src="~/images/tour/gallery/3.jpg" alt=""
                                 class="img-fluid blur-up lazyload w-100">
                        </div>
                        <div class="gallery-content">
                            <h3>garden</h3>
                            <div class="rating">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="view-cls"><i class="fas fa-plus"></i></div>
                    </div>
                </a>
            </div>
            <div class="col-3 p-0">
                <a href="~/images/tour/gallery/4.jpg" class="img-box">
                    <div class="gallery_box">
                        <div class="gallery-img">
                            <div class="overlay"></div>
                            <img src="~/images/tour/gallery/4.jpg" alt=""
                                 class="img-fluid blur-up lazyload w-100">
                        </div>
                        <div class="gallery-content">
                            <h3>bangkok night</h3>
                            <div class="rating">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="view-cls"><i class="fas fa-plus"></i></div>
                    </div>
                </a>
            </div>
            <div class="col-2 p-0">
                <a href="~/images/tour/gallery/5.jpg" class="img-box">
                    <div class="gallery_box">
                        <div class="gallery-img">
                            <div class="overlay"></div>
                            <img src="~/images/tour/gallery/5.jpg" alt=""
                                 class="img-fluid blur-up lazyload w-100">
                        </div>
                        <div class="gallery-content">
                            <h3>indian zoo</h3>
                            <div class="rating">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="view-cls"><i class="fas fa-plus"></i></div>
                    </div>
                </a>
                <a href="~/images/tour/gallery/6.jpg" class="img-box">
                    <div class="gallery_box">
                        <div class="gallery-img">
                            <div class="overlay"></div>
                            <img src="~/images/tour/gallery/6.jpg" alt=""
                                 class="img-fluid blur-up lazyload w-100">
                        </div>
                        <div class="gallery-content">
                            <h3>sunset lake</h3>
                            <div class="rating">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="view-cls"><i class="fas fa-plus"></i></div>
                    </div>
                </a>
            </div>
            <div class="col-5 p-0">
                <a href="~/images/tour/gallery/1.jpg" class="img-box">
                    <div class="gallery_box">
                        <div class="gallery-img">
                            <div class="overlay"></div>
                            <img src="~/images/tour/gallery/1.jpg" alt=""
                                 class="img-fluid blur-up lazyload w-100">
                        </div>
                        <div class="gallery-content">
                            <h3>span water fall</h3>
                            <div class="rating">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="far fa-star"></i>
                            </div>
                        </div>
                        <div class="view-cls"><i class="fas fa-plus"></i></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
<!-- gallery section end -->
<vc:popular-destination></vc:popular-destination>
<vc:blog></vc:blog>
<!-- subscribe section start -->
<section class="subscribe_section medium-section">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-6">
                <div class="subscribe-detail">
                    <div>
                        <h2>subscribe our news <span>our news</span></h2>
                        <p>
                            Subscribe and receive our newsletters to follow the news about our fresh and fantastic
                            products
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-xl-7 col-lg-6">
                <div class="input-section">
                    <input type="text" class="form-control" placeholder="Enter Your Email"
                           aria-label="Recipient's username">
                    <a href="#" class="btn btn-rounded btn-sm color1">subscribe</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- subscribe section end -->


@section Scripts {

}